openapi: 3.1.0
info:
  version: 1.0.0
  title: Aquatrack app
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    This is a documentation of Aquatrack app
tags:
  - name: User
    description: Operations about users.
  - name: Auth
    description: Auth operations.
  - name: Water
    description: Operations about water.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /users/register:
    post:
      $ref: ../swagger/paths/users/register/post.yaml
  /users/login:
    post:
      $ref: ../swagger/paths/users/login/post.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/users/logout/post.yaml
  /users/refresh:
    post:
      $ref: ../swagger/paths/users/refresh/post.yaml
  /user:
    get:
      $ref: ../swagger/paths/user/get.yaml
    patch:
      $ref: ../swagger/paths/user/patch.yaml

  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water:
    get:
      $ref: ../swagger/paths/water/get.yaml
    post:
      $ref: ../swagger/paths/water/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
